import { PrismaClient } from '@prisma/client';
import { whatsappService } from './whatsapp';
import { openaiService, Intent } from './openai';
import cron from 'node-cron';

const prisma = new PrismaClient();

export interface WebhookMessage {
  phone: string;
  message: string;
  timestamp?: string;
  clientSlug?: string;
}

export class WhatsAppHandler {
  async processIncomingMessage(data: WebhookMessage): Promise<void> {
    const { phone, message, clientSlug } = data;

    console.log(`[WhatsApp Handler] Mensaje recibido de ${phone}: ${message}`);

    if (!clientSlug) {
      console.error('[WhatsApp Handler] clientSlug no proporcionado');
      return;
    }

    // 1. Find the client and WhatsApp config
    const client = await prisma.client.findUnique({
      where: { slug: clientSlug },
      include: { whatsappConfig: true },
    });

    if (!client || !client.whatsappConfig || !client.whatsappConfig.isActive) {
      console.error(`[WhatsApp Handler] Cliente ${clientSlug} no tiene WhatsApp configurado`);
      return;
    }

    const config = client.whatsappConfig;

    // 2. Log incoming message
    await this.logMessage(client.id, phone, 'INBOUND', message);

    // 3. Get business context
    const [services, workingHours, customerBookings] = await Promise.all([
      prisma.service.findMany({
        where: { clientId: client.id, isActive: true },
        select: { name: true, description: true, duration: true, price: true },
      }),
      prisma.workingHours.findMany({
        where: { clientId: client.id },
        select: { dayOfWeek: true, openTime: true, closeTime: true, isOpen: true },
      }),
      prisma.booking.findMany({
        where: {
          clientId: client.id,
          customerPhone: phone,
          status: { in: ['PENDING', 'CONFIRMED'] },
        },
        include: { service: { select: { name: true } } },
        orderBy: { date: 'asc' },
        take: 10,
      }),
    ]);

    const existingBookings = customerBookings.map(b => ({
      id: b.id,
      date: b.date.toISOString().split('T')[0],
      startTime: b.startTime,
      endTime: b.endTime,
      status: b.status,
      serviceName: b.service.name,
    }));

    // 4. Analyze message with OpenAI
    const parsed = await openaiService.analyzeMessage(
      message,
      client.name,
      services,
      workingHours,
      existingBookings,
      config.aiPersonality
    );

    console.log(`[WhatsApp Handler] Intención detectada: ${parsed.intent}`);

    // 5. Execute action based on intent
    let responseText = parsed.response;
    let bookingId: string | undefined;

    switch (parsed.intent) {
      case 'BOOKING':
        const bookingResult = await this.handleBooking(client.id, client.slug, phone, parsed);
        if (bookingResult.success) {
          responseText = bookingResult.message;
          bookingId = bookingResult.bookingId;
        } else {
          responseText = bookingResult.message;
        }
        break;

      case 'CANCEL':
        const cancelResult = await this.handleCancel(client.id, phone, parsed);
        responseText = cancelResult.message;
        break;

      case 'CONFIRM':
        const confirmResult = await this.handleConfirm(client.id, phone, parsed);
        responseText = confirmResult.message;
        break;

      case 'INFO':
      case 'GREETING':
      case 'UNKNOWN':
        // Response already generated by OpenAI
        break;
    }

    // 6. Send response via WhatsApp
    await whatsappService.sendMessage(phone, responseText, {
      phoneNumberId: config.phoneNumberId,
      apiKey: config.apiKey,
      instanceId: config.instanceId || undefined,
    });

    // 7. Log outgoing message
    await this.logMessage(client.id, phone, 'OUTBOUND', responseText, parsed.intent, bookingId);
  }

  private async handleBooking(
    clientId: string,
    clientSlug: string,
    phone: string,
    parsed: Awaited<ReturnType<typeof openaiService.analyzeMessage>>
  ): Promise<{ success: boolean; message: string; bookingId?: string }> {
    const { data } = parsed;

    if (!data?.serviceName || !data?.date || !data?.time) {
      return {
        success: false,
        message: '¿Qué servicio te gustaría reservar? Por favor, dime el servicio, la fecha y la hora que prefieres.',
      };
    }

    // Find the service
    const service = await prisma.service.findFirst({
      where: {
        clientId,
        name: { contains: data.serviceName },
        isActive: true,
      },
    });

    if (!service) {
      return {
        success: false,
        message: `No encontré el servicio "${data.serviceName}". ¿Podrías verificar el nombre?`,
      };
    }

    // Check availability
    const bookingDate = new Date(data.date);
    const startTime = data.time;
    const [hours, minutes] = startTime.split(':').map(Number);
    const endMinutes = hours * 60 + minutes + service.duration;
    const endTime = `${Math.floor(endMinutes / 60).toString().padStart(2, '0')}:${(endMinutes % 60).toString().padStart(2, '0')}`;

    // Check for conflicts
    const conflict = await prisma.booking.findFirst({
      where: {
        clientId,
        date: bookingDate,
        status: { not: 'CANCELLED' },
        startTime: { lt: endTime },
        endTime: { gt: startTime },
      },
    });

    if (conflict) {
      return {
        success: false,
        message: `Lo siento, ese horario ya está ocupado. ¿Te gustaría elegir otro horario?`,
      };
    }

    // Create the booking
    const booking = await prisma.booking.create({
      data: {
        customerName: data.customerName || 'Cliente WhatsApp',
        customerPhone: phone,
        date: bookingDate,
        startTime,
        endTime,
        status: 'CONFIRMED',
        notes: 'Reservado vía WhatsApp',
        clientId,
        serviceId: service.id,
      },
    });

    const formattedDate = bookingDate.toLocaleDateString('es-ES', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    return {
      success: true,
      message: `¡Tu cita ha sido reservada! 🎉\n\n*Servicio:* ${service.name}\n*Fecha:* ${formattedDate}\n*Hora:* ${startTime}\n*Duración:* ${service.duration} minutos\n\n¡Te esperamos!`,
      bookingId: booking.id,
    };
  }

  private async handleCancel(
    clientId: string,
    phone: string,
    parsed: Awaited<ReturnType<typeof openaiService.analyzeMessage>>
  ): Promise<{ success: boolean; message: string }> {
    // Find the next upcoming booking for this phone number
    const booking = await prisma.booking.findFirst({
      where: {
        clientId,
        customerPhone: phone,
        status: { in: ['PENDING', 'CONFIRMED'] },
        date: { gte: new Date() },
      },
      include: { service: { select: { name: true } } },
      orderBy: [{ date: 'asc' }, { startTime: 'asc' }],
    });

    if (!booking) {
      return {
        success: false,
        message: 'No encontré ninguna cita activa para cancelar.',
      };
    }

    await prisma.booking.update({
      where: { id: booking.id },
      data: { status: 'CANCELLED' },
    });

    return {
      success: true,
      message: `Tu cita de *${booking.service.name}* el ${booking.date.toLocaleDateString('es-ES')} a las ${booking.startTime} ha sido cancelada.`,
    };
  }

  private async handleConfirm(
    clientId: string,
    phone: string,
    parsed: Awaited<ReturnType<typeof openaiService.analyzeMessage>>
  ): Promise<{ success: boolean; message: string }> {
    const booking = await prisma.booking.findFirst({
      where: {
        clientId,
        customerPhone: phone,
        status: 'PENDING',
        date: { gte: new Date() },
      },
      include: { service: { select: { name: true } } },
      orderBy: [{ date: 'asc' }, { startTime: 'asc' }],
    });

    if (!booking) {
      return {
        success: false,
        message: 'No encontré ninguna cita pendiente por confirmar.',
      };
    }

    await prisma.booking.update({
      where: { id: booking.id },
      data: { status: 'CONFIRMED' },
    });

    return {
      success: true,
      message: `¡Tu cita de *${booking.service.name}* ha sido confirmada! Te esperamos el ${booking.date.toLocaleDateString('es-ES')} a las ${booking.startTime}.`,
    };
  }

  private async logMessage(
    clientId: string,
    phone: string,
    direction: 'INBOUND' | 'OUTBOUND',
    message: string,
    intent?: string,
    bookingId?: string
  ): Promise<void> {
    try {
      await prisma.whatsAppLog.create({
        data: {
          clientId,
          phoneNumber: phone,
          direction,
          message,
          intent: intent || null,
          bookingId: bookingId || null,
        },
      });
    } catch (error) {
      console.error('[WhatsApp Handler] Error guardando log:', error);
    }
  }

  startReminderScheduler(): void {
    // Run every 30 minutes
    cron.schedule('*/30 * * * *', async () => {
      console.log('[Scheduler] Verificando recordatorios...');
      await this.sendReminders();
      await this.sendFollowUps();
    });

    console.log('[Scheduler] Programa de recordatorios iniciado');
  }

  private async sendReminders(): Promise<void> {
    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    tomorrow.setHours(0, 0, 0, 0);

    const endOfTomorrow = new Date(tomorrow);
    endOfTomorrow.setHours(23, 59, 59, 999);

    const upcomingBookings = await prisma.booking.findMany({
      where: {
        status: 'CONFIRMED',
        date: { gte: tomorrow, lte: endOfTomorrow },
        customerPhone: { not: null },
      },
      include: {
        service: { select: { name: true } },
        client: {
          include: { whatsappConfig: true },
        },
      },
    });

    for (const booking of upcomingBookings) {
      if (!booking.customerPhone || !booking.client.whatsappConfig) continue;

      const config = booking.client.whatsappConfig;
      if (!config.isActive || !config.isOpenAIEnabled) continue;

      const message = await openaiService.generateReminderMessage(
        booking.client.name,
        booking.customerName,
        booking.service.name,
        booking.date.toLocaleDateString('es-ES'),
        booking.startTime
      );

      await whatsappService.sendMessage(booking.customerPhone, message, {
        phoneNumberId: config.phoneNumberId,
        apiKey: config.apiKey,
        instanceId: config.instanceId || undefined,
      });

      await this.logMessage(
        booking.clientId,
        booking.customerPhone,
        'OUTBOUND',
        message,
        'REMINDER'
      );
    }
  }

  private async sendFollowUps(): Promise<void> {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const endOfToday = new Date(today);
    endOfToday.setHours(23, 59, 59, 999);

    const completedBookings = await prisma.booking.findMany({
      where: {
        status: 'COMPLETED',
        date: { gte: today, lte: endOfToday },
        customerPhone: { not: null },
      },
      include: {
        service: { select: { name: true } },
        client: {
          include: { whatsappConfig: true },
        },
      },
    });

    for (const booking of completedBookings) {
      if (!booking.customerPhone || !booking.client.whatsappConfig) continue;

      const config = booking.client.whatsappConfig;
      if (!config.isActive || !config.isOpenAIEnabled) continue;

      const message = await openaiService.generateFollowUpMessage(
        booking.client.name,
        booking.customerName,
        booking.service.name
      );

      await whatsappService.sendMessage(booking.customerPhone, message, {
        phoneNumberId: config.phoneNumberId,
        apiKey: config.apiKey,
        instanceId: config.instanceId || undefined,
      });

      await this.logMessage(
        booking.clientId,
        booking.customerPhone,
        'OUTBOUND',
        message,
        'FOLLOWUP'
      );
    }
  }
}

export const whatsappHandler = new WhatsAppHandler();
