import type { Config } from 'tailwindcss';

/** Paleta: #0f172a (oscuro), #2dd4bf (acento), #64748b (neutro) */
const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-background': '#0f172a',
        'surface-bright': '#f8fafc',
        'primary': '#2dd4bf',
        'outline': '#64748b',
        'inverse-surface': '#0f172a',
        'on-primary': '#0f172a',
        'surface-container': '#e2e8f0',
        'inverse-on-surface': '#f8fafc',
        'primary-fixed': '#ccfbf1',
        'on-secondary-fixed-variant': '#334155',
        'outline-variant': '#cbd5e1',
        'surface-variant': '#e2e8f0',
        'on-primary-fixed': '#042f2e',
        'secondary-fixed': '#e2e8f0',
        'on-primary-container': '#0f172a',
        'secondary-fixed-dim': '#94a3b8',
        'surface-tint': '#2dd4bf',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#5eead4',
        'background': '#f8fafc',
        'on-tertiary': '#ffffff',
        'surface-dim': '#cbd5e1',
        'primary-container': '#99f6e4',
        'on-surface-variant': '#64748b',
        'tertiary-fixed-dim': '#94a3b8',
        'on-tertiary-fixed': '#0f172a',
        'on-secondary': '#ffffff',
        'surface': '#f8fafc',
        'on-error-container': '#93000a',
        'on-primary-fixed-variant': '#0f766e',
        'tertiary-fixed': '#e2e8f0',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#0f172a',
        'on-tertiary-fixed-variant': '#334155',
        'on-tertiary-container': '#0f172a',
        'tertiary': '#475569',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#5eead4',
        'on-secondary-container': '#0f172a',
        'secondary': '#64748b',
        'tertiary-container': '#cbd5e1',
        'surface-container-highest': '#e2e8f0',
        'error': '#ba1a1a',
        'on-surface': '#0f172a',
        'surface-container-low': '#f1f5f9',
        'secondary-container': '#e2e8f0',
        'surface-container-high': '#e2e8f0',
      },
      borderRadius: {
        DEFAULT: '8px',
        lg: '12px',
        xl: '16px',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '64px',
        'unit': '4px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '40px',
        'gutter': '24px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'headline-xl': ['Manrope', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
        'headline-lg-mobile': ['Manrope', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
export default config;
