import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-background': '#191c1e',
        'surface-bright': '#f8f9fc',
        'primary': '#5950b6',
        'outline': '#787583',
        'inverse-surface': '#2e3133',
        'on-primary': '#ffffff',
        'surface-container': '#edeef1',
        'inverse-on-surface': '#f0f1f4',
        'primary-fixed': '#e4dfff',
        'on-secondary-fixed-variant': '#00513f',
        'outline-variant': '#c8c4d4',
        'surface-variant': '#e1e2e5',
        'on-primary-fixed': '#150066',
        'secondary-fixed': '#9ef3d6',
        'on-primary-container': '#32258d',
        'secondary-fixed-dim': '#82d7ba',
        'surface-tint': '#5950b6',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#c6c0ff',
        'background': '#f8f9fc',
        'on-tertiary': '#ffffff',
        'surface-dim': '#d9dadd',
        'primary-container': '#9d94ff',
        'on-surface-variant': '#474552',
        'tertiary-fixed-dim': '#eabea0',
        'on-tertiary-fixed': '#2d1604',
        'on-secondary': '#ffffff',
        'surface': '#f8f9fc',
        'on-error-container': '#93000a',
        'on-primary-fixed-variant': '#41369d',
        'tertiary-fixed': '#ffdcc5',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#002118',
        'on-tertiary-fixed-variant': '#5f402a',
        'on-tertiary-container': '#4e311c',
        'tertiary': '#79573f',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#c6c0ff',
        'on-secondary-container': '#0b7059',
        'secondary': '#006b55',
        'tertiary-container': '#c2997e',
        'surface-container-highest': '#e1e2e5',
        'error': '#ba1a1a',
        'on-surface': '#191c1e',
        'surface-container-low': '#f2f3f6',
        'secondary-container': '#9bf0d3',
        'surface-container-high': '#e7e8eb',
      },
      borderRadius: {
        DEFAULT: '8px',
        lg: '12px',
        xl: '16px',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '64px',
        'unit': '4px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '40px',
        'gutter': '24px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'headline-xl': ['Manrope', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
        'headline-lg-mobile': ['Manrope', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
export default config;
